language: python
python:
  - 2.7
sudo: false
env:
  matrix:
    - TOX_ENV=py27
    - TOX_ENV=py34
before_install: 
  - wget https://7de4dfdec62155b49b44-d726a73613a1989d29b147f20996e7c1.ssl.cf2.rackcdn.com/mathjax.zip
  - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
  - pip install tox
  - pip install -f travis-wheels/wheelhouse file://$PWD#egg=bitjet
script:
  - tox -e $TOX_ENV
